2019-07-17T21:32:31|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:/Users/MurthyLab/Desktop/AntCam-master/main_interface.py", line 61, in <module>
    app = AntCamApp(sys.argv)
  File "C:\Users\MurthyLab\Anaconda3\lib\site-packages\ScopeFoundry\base_app.py", line 332, in __init__
    self.setup()
  File "C:/Users/MurthyLab/Desktop/AntCam-master/main_interface.py", line 46, in setup
    self.add_measurement(SelinaTraining(self))
  File "C:\Users\MurthyLab\Anaconda3\lib\site-packages\ScopeFoundry\measurement.py", line 93, in __init__
    self.setup()
  File "C:\Users\MurthyLab\Desktop\AntCam-master\AntCamMS\Selina_Contingency.py", line 103, in setup
    self.vc = cv2.VideoCapture(0)
NameError: name 'cv2' is not defined

