2019-07-17T14:11:44|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\MurthyLab\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\Users\MurthyLab\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\MurthyLab\Desktop\AntCam-master\AntCamHW\flircam\flircam_hw.py", line 31, in connect
    self._dev=FLIRCamDev(self.settings.camera_sn.value())
TypeError: 'str' object is not callable

2019-07-17T14:11:44|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\MurthyLab\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\Users\MurthyLab\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\MurthyLab\Desktop\AntCam-master\AntCamHW\flircam\flirrec_hw.py", line 25, in connect
    self._dev=FLIRRecDev(self.settings.path.value())
TypeError: 'str' object is not callable

